version: '3'
services:
  webserver:
    image: nginx
    ports:
      - 83:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web/:/var/www/html
    depends_on:
      - php
    command: /bin/bash -c "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  php:
    image: php:7.4-fpm
    volumes:
      - ./web/:/var/www/html
